### ISSUE TITLE
SelectableTextBlock does not work

### ISSUE THREAD

**Issue by tomlm** [jinek/Consolonia#203]
Added in Avalonia 11
https://docs.avaloniaui.net/docs/reference/controls/selectable-textblock

**Comment by jinek** [comment]
Linux needs special behavior because SelectableTextBlock process the selection when mouse is moved over the text, but linux tty does not send mouse move event.
Thus, on linux we need to handle PointerRelease event and set SelectionStart/End manually.

I could not test, but probably Windows part is working now. Should be visible in GalleryTextBlock page.

**Comment by tomlm** [comment]
Windows works great btw
