### ISSUE TITLE
Left/Right Cursor keys navigate outside of input controls 

### ISSUE THREAD

**Issue by tomlm** [jinek/Consolonia#213]
# Repo
1. go to TextBox gallery page
2. Click in TextBox....type a bunch of chars.
3. Now cursor back and forth. When you cursor to the end of the text it stops. 
4. When you cursor to the front of the text it moves the focus away from the input control.

# Expected
That it behaves the way Avalonia does, which is to keep focus in input control.

**Comment by jinek** [comment]
That's probably because of `ArrowsAndKeyboardNavigationHandler`: if arrow key is not handled then it focuses an element at the direction of an arrow. We can switch it off by default since we implemented accesskey. May be would be a good option to add additional assembly, like, Consolonia.Addons for such kind of additional stuff.

**Comment by jinek** [comment]
Goes together with https://github.com/jinek/Consolonia/issues/185
