### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by jinek** [jinek/Consolonia#7]
Setup rules of code style and re-format/validate by jetbrains tools (including duplication finder).

**Comment by vabka** [comment]
Look at https://github.com/dotnet/format
Editorconfig from it can be shared with R# and you can use dotnet-format instead of default R# formatter.

Duplication finder: https://www.jetbrains.com/help/resharper/dupFinder.html
But i dont know how it can be run in gh actions.
In teamcity there is a default step for R# tools. But i dont know is it available for OSS.

**Comment by jinek** [comment]
I will create separate task for dupFinder. It's probably not ~one liner like inspections and formatting
